events {
    worker_connections 1024;
}

http {

    upstream autor-ms {
        server autor-ms:8082;
    }

    upstream livro-ms {
        server livro-ms:8081;
    }

    upstream front-ms {
        server front-ms:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://front-ms;
        }

        location /api/autores {
            proxy_pass http://autor-ms/api/autores;
        }

        location /api/livros {
            proxy_pass http://livro-ms/api/livros;
        }
    }
}